export const SERVER_URL = 'http://192.168.100.9:1337';
//http://192.168.100.9:1337
//http://localhost:1337
export const actionTypes = {
	FETCH_BLOGS: 'FETCH_BLOGS',
	FETCH_BLOGS_SUCCESSFUL: 'FETCH_BLOGS_SUCCESSFUL',
	FETCH_BLOGS_FAILED: 'FETCH_BLOGS_FAILED',
	REQUEST_ADD_BLOG: 'REQUEST_ADD_BLOG',
	ADD_BLOG: 'ADD_BLOG',
	REQUEST_DELETE_BLOG: 'REQUEST_DELETE_BLOG',
	DELETE_BLOG: 'DELETE_BLOG',
	FAILED_REQUEST: 'FAILED_REQUEST',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	SET_SEARCH_PARAM: 'SET_SEARCH_PARAM'
}