export const SERVER_URL = 'http://192.168.100.9:1337';
//http://192.168.100.9:1337
//http://localhost:1337

export const actionTypes = {
	REQUEST_LOGIN: 'REQUEST_LOGIN',
	LOGIN: 'LOGIN',
	REQUEST_LOGOUT: 'REQUEST_LOGOUT',
	LOGOUT: 'LOGOUT',
	REQUEST_REGISTER: 'REQUEST_REGISTER',
	REGISTER: 'REGISTER',
	FETCH_BLOGS: 'FETCH_BLOGS',
	FETCH_BLOGS_SUCCESSFUL: 'FETCH_BLOGS_SUCCESSFUL',
	FETCH_BLOGS_FAILED: 'FETCH_BLOGS_FAILED',
	REQUEST_ADD_BLOG: 'REQUEST_ADD_BLOG',
	ADD_BLOG: 'ADD_BLOG',
	REQUEST_DELETE_BLOG: 'REQUEST_DELETE_BLOG',
	DELETE_BLOG: 'DELETE_BLOG',
	FAILED_REQUEST: 'FAILED_REQUEST',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	SET_SEARCH_PARAM: 'SET_SEARCH_PARAM'
};

export const APP_STATE_KEY = 'appState';
export const CACHE_EXPIRING_KEY = 'cacheExpiring';
export const CACHE_EXPIRING_MINUTES = 20;